export const ErrorCodes = {
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_REQUIRED: 'AUTH_REQUIRED',

  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_INVALID_DATA: 'ACCOUNT_INVALID_DATA',

  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_LIMIT_REACHED: 'PROFILE_LIMIT_REACHED',
  PROFILE_INVALID_DATA: 'PROFILE_INVALID_DATA',
  PROFILE_PRIVATE: 'PROFILE_PRIVATE',

  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_ALREADY_SAVED: 'CONTACT_ALREADY_SAVED',
  CONTACT_INVALID_DATA: 'CONTACT_INVALID_DATA',

  PUBLIC_PROFILE_NOT_ACCESSIBLE: 'PUBLIC_PROFILE_NOT_ACCESSIBLE',

  INVALID_UUID: 'INVALID_UUID',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',

  RATE_LIMITED: 'RATE_LIMITED',

  VALIDATION_FAILED: 'VALIDATION_FAILED',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
